apiVersion: v1
data:
  "volume-extend": "true"
  "volume-health": "true"
  "online-volume-extend": "true"
  "file-volume": "false"
  "csi-sv-feature-states-replication": "true"
kind: ConfigMap
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  namespace: vmware-system-csi